### ISSUE TITLE
feat(api): enable API key authentication layer

### ISSUE THREAD

**Issue by Vaish24navi** [qreater/Tartarus#24]
## Description

Usage of `API-KEY` would add an extra layer of authentication for secure CRUDL operations.

### Tasks
- [x] Write a middleware which authenticates each request with the `API-KEY` supplied.
- [x] Handle cases if `API-KEY` is not supplied
- [x] Applying the best practices to supply `API-KEY` for each requests.
- [x] Testing out all the current APIs with `API-KEY` enabled.

Please select the type of issue:

- [ ] Bug Report
- [X] Feature Request
